### ISSUE TITLE
Translation: French

### ISSUE THREAD

**Issue by ChialiT** [privacy-scaling-explorations/website-v2#124]
Open for translation on the following page:

Home page
Project lib
Resource
About
How:
Navigate to https://github.com/privacy-scaling-explorations/website-v2/tree/main/app/i18n/locales
Duplicate the "en" folder for translation.

I hope this will be a group collaboration effort; if you have any questions, please leave comments.

**Comment by ChialiT** [comment]
> I can have a look at it!

Thank you! @rrtoledo I think sinaxyz wants to help too :)

**Comment by rrtoledo** [comment]
Great! I have just started, any help is more than welcome! I'll push soon :)

**Comment by rrtoledo** [comment]
So far I have been using a more formal language using "vous", and made the choice to use the french phrases with some english here and there: preuve à divulgation nulle de connaissance (c.f. zk-proof).

**Comment by rrtoledo** [comment]
See PR https://github.com/privacy-scaling-explorations/website-v2/pull/140

**Comment by kalidiagne** [comment]
Closing as fixed by this PR https://github.com/privacy-scaling-explorations/website-v2/pull/140
ty @rrtoledo!
