### ISSUE TITLE
Translation: German

### ISSUE THREAD

**Issue by th4s** [privacy-scaling-explorations/website-v2#127]
Open for translation on the following page:

Home page
Project lib
Resource
About
How:
Navigate to https://github.com/privacy-scaling-explorations/website-v2/tree/main/app/i18n/locales
Duplicate the "en" folder for translation.

I hope this will be a group collaboration effort; if you have any questions, please leave comments.

**Comment by th4s** [comment]
Will be closed by #129.

**Comment by kalidiagne** [comment]
closed by https://github.com/privacy-scaling-explorations/website-v2/pull/129
