### ISSUE TITLE
Automate "Last Updated" Date Display

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/website-v2#47]
### Current behavior
The "last updated" date is hard-coded as shown below:

https://github.com/privacy-scaling-explorations/website-v2/blob/26251d62f5dfcd69c78c70e14e72a27567598b04/components/site-footer.tsx#L86
https://github.com/privacy-scaling-explorations/website-v2/blob/26251d62f5dfcd69c78c70e14e72a27567598b04/components/site-header-mobile.tsx#L110

It doesn't reflect the actual last update unless manually updated.

### Proposed behavior
Automate the "last updated" date so that it updates dynamically with each deployment.

Possible solutions:

    * Use CI tool to update this during each deployment

**Comment by ChialiT** [comment]
this feature no longer avaliable. wont fix.
