### ISSUE TITLE
Feature Request: random sorting in project list

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/website-v2#67]
Current: fixed order in the project library list [RLN, Zkitter, MACI...] every time the page is refreshed 

Desired: random sorting whenever the page is refreshed. This helps to balance visibility of projects

**Comment by ChialiT** [comment]
Thank you opening the issue, this feature is already in the todo :)

**Comment by ChialiT** [comment]
random sorting #45
