### ISSUE TITLE
Develop "about" page

### ISSUE THREAD

**Issue by ChialiT** [privacy-scaling-explorations/website-v2#72]
https://www.figma.com/file/wyV1DA4B3b3v8a9grrS5Kl/PSE-Website---2023?type=design&node-id=5214-32959&mode=dev

**Comment by kalidiagne** [comment]
- [ ] https://github.com/privacy-scaling-explorations/website-v2/pull/82

**Comment by kalidiagne** [comment]
solved here https://github.com/privacy-scaling-explorations/website-v2/pull/82
